// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: clientelogistica/clientelogistica.proto

package clientelogistica

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDPedido       string `protobuf:"bytes,1,opt,name=IDPedido,proto3" json:"IDPedido,omitempty"`
	NombreProducto string `protobuf:"bytes,2,opt,name=NombreProducto,proto3" json:"NombreProducto,omitempty"`
	ValorProducto  int32  `protobuf:"varint,3,opt,name=ValorProducto,proto3" json:"ValorProducto,omitempty"`
	Tipo           string `protobuf:"bytes,4,opt,name=Tipo,proto3" json:"Tipo,omitempty"` //retail, normal (pyme), prioritario (pyme)
	Destino        string `protobuf:"bytes,5,opt,name=Destino,proto3" json:"Destino,omitempty"`
	Origen         string `protobuf:"bytes,6,opt,name=Origen,proto3" json:"Origen,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientelogistica_clientelogistica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_clientelogistica_clientelogistica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_clientelogistica_clientelogistica_proto_rawDescGZIP(), []int{0}
}

func (x *Pedido) GetIDPedido() string {
	if x != nil {
		return x.IDPedido
	}
	return ""
}

func (x *Pedido) GetNombreProducto() string {
	if x != nil {
		return x.NombreProducto
	}
	return ""
}

func (x *Pedido) GetValorProducto() int32 {
	if x != nil {
		return x.ValorProducto
	}
	return 0
}

func (x *Pedido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Pedido) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Pedido) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

type Seguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodigoSeguimiento int64 `protobuf:"varint,1,opt,name=CodigoSeguimiento,proto3" json:"CodigoSeguimiento,omitempty"`
}

func (x *Seguimiento) Reset() {
	*x = Seguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientelogistica_clientelogistica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seguimiento) ProtoMessage() {}

func (x *Seguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_clientelogistica_clientelogistica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seguimiento.ProtoReflect.Descriptor instead.
func (*Seguimiento) Descriptor() ([]byte, []int) {
	return file_clientelogistica_clientelogistica_proto_rawDescGZIP(), []int{1}
}

func (x *Seguimiento) GetCodigoSeguimiento() int64 {
	if x != nil {
		return x.CodigoSeguimiento
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientelogistica_clientelogistica_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_clientelogistica_clientelogistica_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_clientelogistica_clientelogistica_proto_rawDescGZIP(), []int{2}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_clientelogistica_clientelogistica_proto protoreflect.FileDescriptor

var file_clientelogistica_clientelogistica_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x61, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x22, 0xb8, 0x01, 0x0a, 0x06,
	0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x44, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x44, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x0d, 0x56, 0x61,
	0x6c, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x69, 0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x43, 0x6f, 0x64, 0x69, 0x67, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x32, 0xaa, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x12, 0x48, 0x0a, 0x0b, 0x48, 0x61,
	0x63, 0x65, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x50, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x1a, 0x1d, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61,
	0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1d, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientelogistica_clientelogistica_proto_rawDescOnce sync.Once
	file_clientelogistica_clientelogistica_proto_rawDescData = file_clientelogistica_clientelogistica_proto_rawDesc
)

func file_clientelogistica_clientelogistica_proto_rawDescGZIP() []byte {
	file_clientelogistica_clientelogistica_proto_rawDescOnce.Do(func() {
		file_clientelogistica_clientelogistica_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientelogistica_clientelogistica_proto_rawDescData)
	})
	return file_clientelogistica_clientelogistica_proto_rawDescData
}

var file_clientelogistica_clientelogistica_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_clientelogistica_clientelogistica_proto_goTypes = []interface{}{
	(*Pedido)(nil),      // 0: clientelogistica.Pedido
	(*Seguimiento)(nil), // 1: clientelogistica.Seguimiento
	(*Estado)(nil),      // 2: clientelogistica.Estado
}
var file_clientelogistica_clientelogistica_proto_depIdxs = []int32{
	0, // 0: clientelogistica.ClienteLogistica.HacerPedido:input_type -> clientelogistica.Pedido
	1, // 1: clientelogistica.ClienteLogistica.SolicitarEstado:input_type -> clientelogistica.Seguimiento
	1, // 2: clientelogistica.ClienteLogistica.HacerPedido:output_type -> clientelogistica.Seguimiento
	2, // 3: clientelogistica.ClienteLogistica.SolicitarEstado:output_type -> clientelogistica.Estado
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientelogistica_clientelogistica_proto_init() }
func file_clientelogistica_clientelogistica_proto_init() {
	if File_clientelogistica_clientelogistica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientelogistica_clientelogistica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientelogistica_clientelogistica_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientelogistica_clientelogistica_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientelogistica_clientelogistica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientelogistica_clientelogistica_proto_goTypes,
		DependencyIndexes: file_clientelogistica_clientelogistica_proto_depIdxs,
		MessageInfos:      file_clientelogistica_clientelogistica_proto_msgTypes,
	}.Build()
	File_clientelogistica_clientelogistica_proto = out.File
	file_clientelogistica_clientelogistica_proto_rawDesc = nil
	file_clientelogistica_clientelogistica_proto_goTypes = nil
	file_clientelogistica_clientelogistica_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClienteLogisticaClient is the client API for ClienteLogistica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClienteLogisticaClient interface {
	HacerPedido(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Seguimiento, error)
	SolicitarEstado(ctx context.Context, in *Seguimiento, opts ...grpc.CallOption) (*Estado, error)
}

type clienteLogisticaClient struct {
	cc grpc.ClientConnInterface
}

func NewClienteLogisticaClient(cc grpc.ClientConnInterface) ClienteLogisticaClient {
	return &clienteLogisticaClient{cc}
}

func (c *clienteLogisticaClient) HacerPedido(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Seguimiento, error) {
	out := new(Seguimiento)
	err := c.cc.Invoke(ctx, "/clientelogistica.ClienteLogistica/HacerPedido", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clienteLogisticaClient) SolicitarEstado(ctx context.Context, in *Seguimiento, opts ...grpc.CallOption) (*Estado, error) {
	out := new(Estado)
	err := c.cc.Invoke(ctx, "/clientelogistica.ClienteLogistica/SolicitarEstado", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClienteLogisticaServer is the server API for ClienteLogistica service.
type ClienteLogisticaServer interface {
	HacerPedido(context.Context, *Pedido) (*Seguimiento, error)
	SolicitarEstado(context.Context, *Seguimiento) (*Estado, error)
}

// UnimplementedClienteLogisticaServer can be embedded to have forward compatible implementations.
type UnimplementedClienteLogisticaServer struct {
}

func (*UnimplementedClienteLogisticaServer) HacerPedido(context.Context, *Pedido) (*Seguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HacerPedido not implemented")
}
func (*UnimplementedClienteLogisticaServer) SolicitarEstado(context.Context, *Seguimiento) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarEstado not implemented")
}

func RegisterClienteLogisticaServer(s *grpc.Server, srv ClienteLogisticaServer) {
	s.RegisterService(&_ClienteLogistica_serviceDesc, srv)
}

func _ClienteLogistica_HacerPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pedido)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClienteLogisticaServer).HacerPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientelogistica.ClienteLogistica/HacerPedido",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClienteLogisticaServer).HacerPedido(ctx, req.(*Pedido))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClienteLogistica_SolicitarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Seguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClienteLogisticaServer).SolicitarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientelogistica.ClienteLogistica/SolicitarEstado",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClienteLogisticaServer).SolicitarEstado(ctx, req.(*Seguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClienteLogistica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clientelogistica.ClienteLogistica",
	HandlerType: (*ClienteLogisticaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HacerPedido",
			Handler:    _ClienteLogistica_HacerPedido_Handler,
		},
		{
			MethodName: "SolicitarEstado",
			Handler:    _ClienteLogistica_SolicitarEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientelogistica/clientelogistica.proto",
}
